---
title: "course project 1"
author: "Raul Bossa"
date: "17 de junio de 2020"
output: html_document
---


#Read data
```{r data, include=TRUE}
setwd("C:/Users/USUARIO/Desktop/Specialization/5 reproducible")
data = read.csv("activity.csv", header = TRUE)
```
#Count NA values

```{r na, include=TRUE}
str(data)
NAcon = is.na(data$steps) #only in steps variable
table(NAcon)
```

```{r count, include=TRUE}
count=complete.cases(data) # for the entire dataset
table(count)
```
#Imputing NA
```{r 2, include=TRUE}
class(data$date)
data$date = as.Date(data$date, format = "%Y-%m-%d") #covert to date format 
```

```{r imputing, include=TRUE}
data$steps2 = ifelse (is.na(data$steps),
                      by(data, data$date, FUN = function (x)mean(data$steps, na.rm = TRUE)),
                      data$steps)# puting the mean 


data$steps = NULL
table(complete.cases(data))
```



```{r sum, include=TRUE}
stepsbyday=aggregate(data$steps2, by = list(date = data$date), FUN = sum)
```


```{r hist, include=TRUE}
hist(stepsbyday$x, xlab = "Steps", main = "Histogram of number of steps by day", breaks = "sturges")
```

#mean of steps by day
```{r mean, include=TRUE}
mean(stepsbyday$x)
```
#median of steps by day
```{r median, include=TRUE}
median(stepsbyday$x)
```

#daily pattern
```{r mean2, include=TRUE}
pattern <- aggregate(data$steps2, by = list(interval = data$interval),
               FUN=mean)
```


```{r plot1, include=TRUE}
plot(pattern,type = "l",main = "mean number of steps across all days",
     xlab = "interval", ylab = "Steps")
```

#extract weekday and weekend
```{r, include=TRUE}
data$typeday = ifelse(as.POSIXlt(data$date)$wday %in% c(0,6), "weekends","weekdays")
```

```{r, include=TRUE}
final<-aggregate(steps2 ~ interval + typeday, data=data, mean)
```


```{r plot3, include=TRUE}
library(lattice)
xyplot(steps2~interval|typeday, data=final, type="l",
       layout = c(2,1), main = "Average steps", 
       ylab = "number of steps",xlab = "Interval")
```




